export PACER_HOME=$PWD
export PACER_MODEL_PATH=$PACER_HOME/example/models
export PACER_PLUGIN_PATH=$PACER_HOME/build/example/plugins
export GAZEBO_MODEL_PATH=$PACER_HOME/example/models:$GAZEBO_MODEL_PATH
export GAZEBO_PLUGIN_PATH=$PACER_HOME/build:$GAZEBO_PLUGIN_PATH
