export PACER_HOME=$PWD
export PACER_PLUGIN_PATH=$PACER_HOME/build:$PACER_PLUGIN_PATH
export GAZEBO_MODEL_PATH=$PACER_HOME/example/models:$GAZEBO_MODEL_PATH
export GAZEBO_PLUGIN_PATH=$PACER_HOME/build:$GAZEBO_PLUGIN_PATH
